### ISSUE TITLE
location:setLocation subscription is passed to wrapSubscriptions

### ISSUE THREAD

**Issue by Tyler-Murphy** [yoshuawuyts/choo#321]
### Expected behavior
I'd expect that only user-defined subscriptions are passed to `wrapSubscriptions`.

### Actual behavior
The internal `location:setLocation` subscription is passed, which means users can't enforce their own async control flow without making an exception for this internal subscription.

### Steps to reproduce behavior
```js
  wrapSubscriptions: subscription => {
    return (send, done) => {
      let promise = subscription(Promise.promisify(send))

      if (!isPromise(promise)) {
        throw new Error('subscriptions must return promises')
      }

      promise.catch(done)
    }
  }
```

causes:

```
index.js:92 Uncaught TypeError: _router is not a function(…)(anonymous function) @ index.js:92redraw @ index.js:34
bluebird.js:1546 Unhandled rejection Error: subscriptions must return promises
    at http://localhost:8080/index.js:181:15
    at http://localhost:8080/index.js:897:11
    at http://localhost:8080/index.js:1017:23
    at Array.forEach (native)
    at apply (http://localhost:8080/index.js:1016:23)
    at http://localhost:8080/index.js:894:9
    at Array.forEach (native)
    at Function.start (http://localhost:8080/index.js:872:12)
    at Function.start (http://localhost:8080/index.js:8719:31)
    at renderStartingView (http://localhost:8080/index.js:328:40)
    at Promise.resolve.then.then.then (http://localhost:8080/index.js:337:17)
From previous event:
    at startApp (http://localhost:8080/index.js:337:6)
    at Object.5../api_client.js (http://localhost:8080/index.js:340:1)
    at s (http://localhost:8080/index.js:1:254)
    at e (http://localhost:8080/index.js:1:425)
    at http://localhost:8080/index.js:1:443
```

I might just be misunderstanding how this is supposed to be used.

**Comment by Tyler-Murphy** [comment]
A simpler way to verify the behavior:

```js
  wrapSubscriptions: subscription => {
    console.log(subscription.toString())
    return () => {}
  }
```

logs:

```
function (send, done) {
      cb(function navigate (pathname) {
        send('location:setLocation', { location: pathname }, done)
      })
    }
```

**Comment by yoshuawuyts** [comment]
you're completely right - we should fix this. Merging this issue with #368
