### ISSUE TITLE
Better handle ES6 source

### ISSUE THREAD

**Issue by s3ththompson** [yoshuawuyts/choo#483]
### Expected behavior
`bankai start`, `bankai build`, and `bankai inspect` work with ES6, or produce actionable error messages.

### Actual behavior
When handling ES6 source, `bankai start` fails with:
```
SyntaxError: Invalid assignment while parsing file: /Users/seththompson/code/readrc/viewer/test/index.js
    at JS_Parse_Error.get (eval at <anonymous> (/Users/seththompson/.homebrew/lib/node_modules/bankai/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
```
`bankai build` fails with:
```
11:23:12 🚨  bankai Invalid assignment while parsing file: /Users/seththompson/code/readrc/viewer/test/index.js
```
and `bankai inspect` fails with:
```
TypeError: Cannot read property 'apply' of undefined
    at Stream.method [as destroy] (/Users/seththompson/.homebrew/lib/node_modules/bankai/node_modules/duplexer/index.js:47:38)
    at /Users/seththompson/.homebrew/lib/node_modules/bankai/node_modules/pump/index.js:43:45
    at call (/Users/seththompson/.homebrew/lib/node_modules/bankai/node_modules/pump/index.js:50:3)
    at Array.forEach (native)
    at /Users/seththompson/.homebrew/lib/node_modules/bankai/node_modules/pump/index.js:70:25
    at f (/Users/seththompson/.homebrew/lib/node_modules/bankai/node_modules/once/once.js:25:25)
    at PassThrough.<anonymous> (/Users/seththompson/.homebrew/lib/node_modules/bankai/node_modules/pump/index.js:29:21)
    at PassThrough.f (/Users/seththompson/.homebrew/lib/node_modules/bankai/node_modules/once/once.js:25:25)
    at emitOne (events.js:96:13)
    at PassThrough.emit (events.js:191:7)
```

### Steps to reproduce behavior
Use bankai on files with ES6 source, for example an `index.js`:
```js
const choo = require('choo')
const html = require('choo/html')

var app = choo();
app.route('/', (state, emit) => {
  return html`<body><h1>Hello World</h1></body>`
})
app.mount('body')
```

**Comment by YerkoPalma** [comment]
This seems to be related to bankai, and not choo specifically

**Comment by s3ththompson** [comment]
Oops, meant to file on bankai... will close and reopen there
